on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create .env file
        run: echo "REACT_APP_HASHED_TOKEN=${{ secrets.HASH }}" > dashboard/.env
      - name: build
        run: CI=false && cd dashboard && npm install && npm run build
      - name: deploy to gh-pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dashboard/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
